//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bin")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub rack: i32,
    pub good: Option<Uuid>,
}

impl ActiveModelBehavior for ActiveModel {}
